export const INTERVIEW_CATEGORIES = {
  JOB: 'JOB',
  PERSONAL: 'PERSONAL',
  MOTIVATION: 'MOTIVATION',
} as const;

export const CATEGORY_TITLES = {
  [INTERVIEW_CATEGORIES.JOB]: '직무 역량 면접',
  [INTERVIEW_CATEGORIES.PERSONAL]: '인성면접',
  [INTERVIEW_CATEGORIES.MOTIVATION]: '지원동기 면접',
} as const;

export const CATEGORY_LIST = [
  { id: INTERVIEW_CATEGORIES.JOB, title: CATEGORY_TITLES.JOB },
  { id: INTERVIEW_CATEGORIES.PERSONAL, title: CATEGORY_TITLES.PERSONAL },
  { id: INTERVIEW_CATEGORIES.MOTIVATION, title: CATEGORY_TITLES.MOTIVATION },
];
